export const ERROR_CODES = [
  "INTERNAL_ERROR",
  "INVALID_CONFIG",
  "SIGNATURE_VERIFY_FAILED",
  "KEY_ALLOCATION_FAILED",
  "KEY_REUSE_CONFLICT",
  "KEY_NOT_ACTIVE",
  "HOOK_EXECUTION_FAILED",
  "HOOK_TIMEOUT",
  "HOOK_INVALID_OUTPUT",
  "ADAPTER_NETWORK_ERROR",
  "ADAPTER_TIMEOUT",
  "ADAPTER_AUTH_ERROR",
  "ADAPTER_RATE_LIMITED",
  "ADAPTER_SERVER_ERROR",
  "CACHE_PURGE_FAILED",
  "WAF_RULE_SYNC_FAILED",
  "UPLOAD_RECYCLE_FAILED",
  "UPLOAD_CANCELLED",
  "UPLOAD_STAGE_TIMEOUT",
  "UPLOAD_VALIDATION_FAILED",
  "UPLOAD_INTERRUPTED",
  "PREVIEW_SOURCE_NOT_FOUND",
  "NAME_MAPPING_WRITE_FAILED"
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
